### ISSUE TITLE
query server from jq!

### ISSUE THREAD

**Issue by jnorthrup** [rakoo/jqouch#1]
feature request.  seems like this is where jq can stretch its legs with sorting and group-by

**Comment by rakoo** [comment]
This is exactly what jqouch is: a query server that understands jq scripts and runs them on documents.

Note though that this was done purely as an experiment and I'm not even using CouchDB anymore. If you want to do anything with it, help yourself, but there's very little chance I will.

See the announcement here: http://mail-archives.apache.org/mod_mbox/couchdb-user/201503.mbox/%3c1427555508-sup-4921@kpad%3e
